### ISSUE TITLE
Language support for experiment website

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#145]
We would like to be able to serve our experiment in any language, which involves a few main components:
1. setting up language support on the experiment website
2. setting up language support for the statements including back end and analysis
3. getting translations of content

For simplicity, this issue focuses on 1 and 3 (for the main website, not all the statements)

This is finished when all text displayed on the experiment website is able to be translated, languages can be selected via user settings or some control in our interface, and there are translations for all text to the 10 or so most common languages. This of course means that we will need to support characters (e.g., Chinese) and right to left languages (e.g., Arabic). Tests will check if coverage is complete, and if translations appear out of date. Added automations could include automatically checking and updating translations when possible, or flagging issues with uncertainty in that process. 

It would be good for us to have some sense of which languages we can safely target given the types of automated tools we have access to e.g., google translate and GPT4 etc. Perhaps we should try some validation to make sure that things are reasonable robust.

A question to think about when working on this is which library or approach will best serve our language support needs. I think there are many good options but I am are there are some pros and cons of each. In general we don't want to reinvent wheels that we don't have to, but we also have constraints that we can't easily budge on, so we need to make sure a solution we select works for us.

**Comment by markwhiting** [comment]
@amirrr do you have any prior thoughts on this that are worth including here? 

Notably this extends #53.

**Comment by dankim444** [comment]
@markwhiting @amirrr 

Hi, I'm currently in the process of integrating i18next and ran into a Typescript configuration issue. Here's the error I'm getting in client/tsconfig.node.json: 
<img width="751" alt="Screenshot 2024-06-07 at 16 06 12" src="https://github.com/Watts-Lab/commonsense-platform/assets/135999988/a80dc9de-c4c3-482b-9df5-06d688de5377">

From my understanding, I don't think vite.config.ts file exists, which might explain why the compiler can't read any inputs. I have tried setting allowJs to true in tsconfig.json and manually adding a vite.config.ts file but both attempts did not resolve anything for me.

**Comment by dankim444** [comment]
@markwhiting @amirrr 
Hi, just a few updates. I implemented internationalization for the 10 most popular languages as requested, allowing the text in the main website to be translated based on a selected language in the interface. Feel free to check out my recent commits and leave any suggestions!

I also had a few questions before moving forward. Do you have preferences for how testing for coverage completion should be done (ie. unit tests, e2e, mocking, tools like cypress/jest?)? As for automations, I was thinking of using locize, but I may need to do a bit more research on other localization tools. Let me know what you think.
