### ISSUE TITLE
Treatment of statements is inconsistent

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#150]
This likely has 2 layers: 
1. some statements have trailing punctuation and capitalization (so we aren't cleaning them correctly somewhere in the pipeline)
2. when statements do not have those things, they are displayed without them on the platform. 

I think the behavior we would like is that statements should be stored in a consistent state (i.e., all have trailing punctuation and capitalization or all not have those things) and displayed in a consistent way (i.e., always shown with the first letter capitalized and a period at the end). 

Additionally, I think we want to clean up any existing statements that have these issues without breaking IDs.

To be finished, we should have a test in place that checks that statements are correctly formatted after ingestion and are correctly formatted at render time.

**Comment by JamesPHoughton** [comment]
Steps:
- add a utility function that cleans statements, 
- clean entire db once as a PR to the statements repo, Use raw statements for translation, then clean english language and foreign language statements after translation. May depend on language?
- set up for part of the pipeline for statement ingestion

blockers:
- ~understanding how local, dev, prod dbs relate and how we can move stuff to prod?~
- how should things look in other languages? Some languages don't use capitalization, punctuation, in the same way. 
- Decide where to do this. Should we specify this in the cleaning utility function? Probably not render, but maybe some object that describes the mutations?

**Comment by JamesPHoughton** [comment]
- dealing with edge cases
- will complete by Friday (hopefully)
