### ISSUE TITLE
Add signout button and improve user signin/signout flow

### ISSUE THREAD

**Issue by acao22** [Watts-Lab/commonsense-platform#160]
This issue focuses on addressing all the bugs and limitations of the user signing / signout flow, as mentioned in https://github.com/Watts-Lab/commonsense-platform/issues/158. We thought it would be best to split this off into a compiled separate issue since there are several parts that should be changed, and also new features that could be added.

**Angie's issues:**
- [x] **Edit the page verification link takes you to** - Clicking on the verification page takes you back to the same page where it asks you to enter your email to register/sign in. We want to make the default return page the Dashboard

**Dan's Issues:**
- [x] **Add sign out button** - Since there is a sign in button, maybe the platform could benefit from a sign out button as well? This is just a suggestion. We could probably add this under the delete account button in dashboard > settings.
- [x] **Create separate flows for account registration and sign in** - I think creating an account and signing in should be treated as two separate flows. We can have one button that navigates new users to a registration page where they can enter their email or other required fields, and when the user submits, they can be shown a welcome/success message. Some tests for this would check that there isn't an account registered with the same email and that data entry was successful in the backend. We can keep the current flow for signing in as is, since this just involves entering an email.

**Comment by JamesPHoughton** [comment]
Bug fixes and feature enhancements. Bug fixes are higher priority than new features. Create a new issue for low priority items to allow this issue to focus and close.

- probably can merge the bug fixes soon, @acao22 has a branch but needs to PR. 
- This issue can probs be closed today
