### ISSUE TITLE
Should we let people explain their answers with more detail? 

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#192]
People often want to tell us more about how they answered. Should we let them? 

e.g. here is one voice of participant: 
> IDEA : I would have liked to explain why I answered that way,all the options were limited and did not really apply to what I wanted to convey.

On one hand, I think this is great and could offer an interesting avenue for qualitative analysis. On the other hand, I worry that people might think of it as too onerous and get bogged down by it. 

So, if we were to do it, I'd want it to be optional and perhaps only appear if someone explicitly selected an "other" option for their reason for responding a certain way.

I'm interested to hear others' thoughts on this: @duncanjwatts @joshnguyen99 @amirrr

**Comment by joshnguyen99** [comment]
I second this proposal! I do not have a good estimate of the prevalence of people who would like to comment, but I often feel the urge to justify why I chose what I chose.

If we make it optional, I don't think it'll hurt at all.

**Comment by duncanjwatts** [comment]
Optional explanation sounds good. Will also limit the number of emails we get.

Duncan Watts (he/him)
Stevens University and PIK Professor 
University of Pennsylvania

https://duncanjwatts.com/
https://css.seas.upenn.edu/

**Comment by amirrr** [comment]
Implemented
![image](https://github.com/user-attachments/assets/eae9eb15-ba0b-4759-84bd-25db8573771b)

**Comment by markwhiting** [comment]
Thanks. Let's see how that works.

I was initially thinking of a per-question response for an "other" option in question 2 or 4, but I think this way of doing it covers more options without being too burdensome to the respondant. The one thing I like about an "Other" option is that it can be designed to only expect a response if selected, but, I think we should see how people use this a bit and reconsider the design later if needed.
