### ISSUE TITLE
Page for adding statements

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#23]
A very simple page that lets them add statements. I don't currently have more structured opinions about how this should work, though it could mirror some of our other elicitation in the future.

**Comment by amirrr** [comment]
Added a draft of user statement adding functionality. Now, users can introduce new statements and provide their opinions on feature labeling.

<img width="1116" alt="Screenshot 2023-11-20 at 4 34 10 in the afternoon" src="https://github.com/Watts-Lab/commonsense-platform/assets/6696894/97a8ae53-8a67-4433-a1b7-d501ebd38f54">

**Comment by markwhiting** [comment]
Cool, perhaps something like: 

> **Add a statement to test:**
> Type here
> **Optional: tell us about your statement**
> {Each of 6 feature questions and category question written in the exact same way they were in the survey — use a question data file so if we need to access that, e.g., for AI, we can use the same structure}
> `Add statement`

Can we use the same style as the rest of the site too. I think we should just keep our styling simple and consistent everywhere.
