### ISSUE TITLE
Estimate AWS running costs

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/Commonsense-Platform#30]
We need to estimate how much it will cost to keep the platform running under load. We should also consider any extreme situations, e.g., if we get public media coverage, how cost sensitive are we to that kind of load? 

- [x] Estimates costs
- [ ] Check in with @regruane to ensure funds are in the right place

**Comment by amirrr** [comment]
We should have a good estimate of the costs by now, seems to be around 60$ to 80$ a month for now.
