### ISSUE TITLE
Add individual response questions, e.g., RME, CRT, demographics

### ISSUE THREAD

**Issue by amirrr** [Watts-Lab/commonsense-platform#54]

**Comment by markwhiting** [comment]
Perhaps do this via integrating just one survey from https://github.com/Watts-Lab/surveys 

e.g., start with RME (multi page and image based survey)

**Comment by markwhiting** [comment]
One more note, we almost certainly want a final page after a person has completed all statements and before they see results that asks for some level of demographics.

**Comment by markwhiting** [comment]
Relates to #58

**Comment by markwhiting** [comment]
Great! I think we should give that a shot.

**Comment by markwhiting** [comment]
These seem like they are on their way to surveys (https://github.com/Watts-Lab/surveys/pull/161). Can that be finalized or is there anything in our way on that?

**Comment by amirrr** [comment]
@markwhiting Regarding CRT, which version do you want to go with? 

I found these:
[CRT-2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5225989/)
[CRT-ALT](https://onlinelibrary.wiley.com/doi/10.1002/bdm.1883)

[Prior exposure to CRT by MTurk participants](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5225989/)
[This one says it's ok](https://link.springer.com/article/10.3758/s13428-017-0963-x)

**Comment by amirrr** [comment]
Added CRT-6 in Surveys.js
[PR #163](https://github.com/Watts-Lab/surveys/pull/163)

**Comment by markwhiting** [comment]
This is done, do you know why it didn't close automatically? (I will close it manually now but do we have some issue stopping things from closing?)
