### ISSUE TITLE
PQ variability and sensitivity evaluation

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/Commonsense-Platform#69]
How repeatable is a given P or Q? That is to say, which of population or corpus play a bigger role in predicting a new PQ point? 

One way to trial this would be to sample a population on two different corpus selections, and then sample two different populations on the same corpus, and see how these differences compare.

**Comment by markwhiting** [comment]
We probably want to check each of these cells to ensure that we aren't making bad assumptions about how the experiment will generalize.

|      | same population | different population |
| ----------- | ----------- | ----------- |
| **same statements**      | checks for repeatability | design point reliability |
| **different statements**   | people's reliability | actual integrative sampling |

**Comment by markwhiting** [comment]
1. Recruit 200 people and give all of them design point A and B in entirely randomized statement order.
2. Randomly split the 200 into 2 groups (G1, G2) of 100 (perhaps try many randomizations to see the mean effect) 
3. Check $PQ(G_1,A) \sim\ PQ(G_1,B)$ — how much does the population predict the outcome on a different design point?
4. Check $PQ(G_1,A) \sim\ PQ(G_2,A)$ — how much does the design point predict the outcome for a different population?

**Comment by markwhiting** [comment]
Might also want to test how different sets of statements $q$ drawn from a single point in $Q$ are or are not repeatable with a similar design.

**Comment by amirrr** [comment]
What would the treatments for this case look like?

**Comment by markwhiting** [comment]
I think the treatment is rather simple: 

1. everyone responds to 30 statements, recruited from Turk. 
2. the statements are sampled from 2 design points, e.g., A and B. And we sample 20 (2 groups of 10) statements from each of A and B (i.e., A1, A2, B1, B2).
3. two treatments: T1: A1, A2 and B1, T2: A1, B1 and B2.

In analysis we do: 
1. between groups T1 ~ T2 on A1 and B1. (we want this to be the same)
2. within subjects (or group) x1 ~ x2 on all participants for whatever set they did two of. (we want this to be the same)
3. within subjects (or group) Ax ~ Bx on all participants for whatever numbers they did. (we want this to be different)

I think the design points should be: 
![Screenshot 2023-08-04 at 10 50 49](https://github.com/Watts-Lab/Commonsense-Platform/assets/673171/e55da293-8099-483f-a14e-b5ccf7bd4178)

I think we should try the new statements to see how they go?

**Comment by markwhiting** [comment]
![untitled-18](https://github.com/Watts-Lab/Commonsense-Platform/assets/673171/ce7aec9a-0f30-4791-8081-a00114fffe3a)

Done! Overall, we see a nice amount of difference between design points and mostly a nice similarity between populations. We also did the same sample with GPT which is less exciting at this point.
