### ISSUE TITLE
Login tweaks

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/Commonsense-Platform#71]
- [x] `Logged in as mark.whiting@gmail.com` is black now, as opposed to white like other text in the same header that it is in.
- [x] After logging in there is nowhere you can go. Perhaps we should show a link that goes to results or dashboard.
- [ ] When signing up to login you are sent back to the survey. I think something that shows up saying something like "Thanks, you are signed up" and doesn't move the user to a new page seems like a reasonable option. I'm open to other designs for this of course.
- [x] I didn't get a confirmation email, but when I tried to log in I got an email pretending to be a confirmation: 
> Thank you for registering with the Common Sense Platform. We're excited to have you on board! To get started, please confirm your account by clicking on the link below...

- [x] Do the login links expire?

**Comment by amirrr** [comment]
Do the login links expire?

No, I can make the links expire-able.

**Comment by markwhiting** [comment]
I don’t think it’s that important for now.
