### ISSUE TITLE
Perhaps we should define common sense better before people start?

### ISSUE THREAD

**Issue by amirrr** [Watts-Lab/commonsense-platform#72]
A user gave this feedback: 
> It made sense, but I think maybe you should give the definition of common sense at the very beginning. For about half of the survey I was thinking of "common sense" in the sense of "a logical conclusion" or "obviously true". Half way through I decided to hover over the ? mark (or was it an i ?) icon and saw that common sense should be interpreted as general knowledge, etc.  So, for example, I said the statement "a battery can't power something forever" was not common sense, since you have to know about batteries/how they work to know that. But it is common knowledge, especially among adults, so having read the definition I would now answer yes it is common sense.

Should we do anything to solve for this?

**Comment by markwhiting** [comment]
Ties to #44
