### ISSUE TITLE
Store urlParams as object

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/Commonsense-Platform#74]
Can we store urlParams as an object as opposed to as the actual params as a string? Is there any disadvantage with doing that?

**Comment by amirrr** [comment]
I don't really understand this, as an object in the database?

**Comment by markwhiting** [comment]
<img width="792" alt="Screenshot 2023-08-01 at 12 04 00" src="https://github.com/Watts-Lab/Commonsense-Platform/assets/673171/f74d1891-875b-4157-94ab-4422a0811fb4">
e.g., statementList is stored as an object and can be parsed as an object, but urlParams is stored as a string and is more annoying to parse. 

I think you can get a JSON version of the urlParams from express directly, but I think that would be more convenient to store. 

What do you think?

**Comment by amirrr** [comment]
Good Idea, it's easier to just JSON.stringify() the object instead of building a string from it. I'll change it.
