### ISSUE TITLE
Look into GPT for statement cleaning & news article statement extraction

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/Commonsense-Platform#78]

**Comment by markwhiting** [comment]
@amirrr — can we do something where we encode the fact that these are GPT refinements and which statement ID they came from? (presumably they get a new ID in our db?)

**Comment by amirrr** [comment]
@markwhiting I added a column to the statements in the database table with source and category as separate columns. Also added the fixed statements to the end of other statements with origId column as the id of the original statement.

**Comment by markwhiting** [comment]
Great, thanks. 

Can we set up a treatment that gets all the statements from our prior design point trial in their new versions, so that we can compare with the data from that earlier trial?
