### ISSUE TITLE
Add testing to platform

### ISSUE THREAD

**Issue by amirrr** [Watts-Lab/commonsense-platform#81]
Looking into running automated browser test with cypress or playwright. They seem to be way to test functionality before deploying to production.

- [x] Testing infrastructure
- [x] Testing main survey flow
- [x] Testing for main page
- [ ] Testing for dashboard
- [ ] Test for all endpoints

**Comment by markwhiting** [comment]
Was thinking more about this, sounds good, lets go ahead with it, and I think it might also be worth adding some tests on the data processing and ingestion side.

**Comment by markwhiting** [comment]
Also we have a cypress account for the lab. We can take a look when we meet.

**Comment by markwhiting** [comment]
Key point is to integrate into commit, build, deploy pipeline

**Comment by markwhiting** [comment]
All done except: 

- [ ] Testing for dashboard calculations
