### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#82]
- [x] Show result component at top
- [x] Make answered statements into clean table
- [x] #90
- [ ] Survey functionality

**Comment by amirrr** [comment]
UI overhaul and dashboard plot ideas (Help wanted!)

<img width="953" alt="Screenshot 2023-11-20 at 4 37 58 in the afternoon" src="https://github.com/Watts-Lab/commonsense-platform/assets/6696894/7203340f-2826-4c70-ae1d-56ecabddc837">
