### ISSUE TITLE
Add statements functionality

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#90]
For this, lets have: 

1. a tab on dashboard that says "add statements" that stands out well
2. a simple ui for writing a statement and adding it
3. a table view like the response table, that shows each thing you've added and the commonsensicality score it achieved.

**Comment by amirrr** [comment]
https://github.com/Watts-Lab/commonsense-platform/issues/23#issuecomment-1819354830



    Add a statement to test:
    Type here
    Optional: tell us about your statement
    {Each of 6 feature questions and category question written in the exact same way they were in the survey — use a question data file so if we need to access that, e.g., for AI, we can use the same structure}
    Add statement

**Comment by markwhiting** [comment]
OOPs perhaps we close one as a duplicate? haha
