### ISSUE TITLE
Ensure we can cope with scale (both technically and from a treatment perspective)

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/commonsense-platform#98]
From a technical standpoint, can we do some tests to see how many users we can handle and think about what to do if we get more users than that? 

From a research standpoint, we should have both extra statements for future treatments preselected, and, a backup treatment if we exhaust everything, so that people still get useful activities.

@amirrr — thoughts on these?

**Comment by amirrr** [comment]
For load testing user capacity, from my initial searching there seems to be some tools like JMeter or Locust to simulate traffic and monitor system performance. You can setup the user journey (complete survey, see result, signup, add statement) and test it with thousands of concurrent users on a local setup that has the same configuration as one of our ECS instances.

Currently we are using this, with no scaling option.
```
"cpu": "256",
"memory": "512",
"runtimePlatform": {
    "cpuArchitecture": "X86_64",
    "operatingSystemFamily": "LINUX"
}
```

**Comment by markwhiting** [comment]
Cool re testing. We should try that just to see. 

For the research point, yeah, it could be other experiments, it could also be extra statements for design points, or getting more ratings for more statements, the key thing is a) nobody gets turned away because of lack of treatments, b) the treatments are good looking (i.e., fallback doesn't include bad statements) and c) it is useful in some way to us.
